open Ascii
open BinNums
open CeresString
open String0

type loc = coq_N

(** val pretty_loc : loc -> string **)

let pretty_loc =
  string_of_N

type error =
| UnmatchedClose of loc
| UnmatchedOpen of loc
| UnknownEscape of loc * ascii
| UnterminatedString of loc
| EmptyInput
| InvalidChar of ascii * loc
| InvalidStringChar of ascii * loc

(** val pretty_error : error -> string **)

let pretty_error = function
| UnmatchedClose p ->
  append (String ((Ascii (true, false, true, false, true, false, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, false, true, true, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, false, true, false, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (false, false, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, false, false, true, false, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (false, false, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)),
    EmptyString))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
    (pretty_loc p)
| UnmatchedOpen p ->
  append (String ((Ascii (true, false, true, false, true, false, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, false, true, true, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, false, true, false, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, false, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (false, false, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, false, false, true, false, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (false, false, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)),
    EmptyString))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
    (pretty_loc p)
| UnknownEscape (p, c) ->
  append (String ((Ascii (true, false, true, false, true, false, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, false, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, false, true, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, true, false, false, true, false,
    false)), (String ((Ascii (false, false, true, true, true, false, true,
    false)), EmptyString)))))))))))))))))))))))))))))))))))))))))))) (String
    (c,
    (append (String ((Ascii (true, true, true, false, false, true, false,
      false)), (String ((Ascii (false, false, false, false, false, true,
      false, false)), (String ((Ascii (true, false, false, false, false,
      true, true, false)), (String ((Ascii (false, false, true, false, true,
      true, true, false)), (String ((Ascii (false, false, false, false,
      false, true, false, false)), (String ((Ascii (false, false, true, true,
      false, true, true, false)), (String ((Ascii (true, true, true, true,
      false, true, true, false)), (String ((Ascii (true, true, false, false,
      false, true, true, false)), (String ((Ascii (true, false, false, false,
      false, true, true, false)), (String ((Ascii (false, false, true, false,
      true, true, true, false)), (String ((Ascii (true, false, false, true,
      false, true, true, false)), (String ((Ascii (true, true, true, true,
      false, true, true, false)), (String ((Ascii (false, true, true, true,
      false, true, true, false)), (String ((Ascii (false, false, false,
      false, false, true, false, false)),
      EmptyString)))))))))))))))))))))))))))) (pretty_loc p))))
| UnterminatedString p ->
  append (String ((Ascii (true, false, true, false, true, false, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, true, true, false, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (false, false, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (true, true, true, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)),
    EmptyString))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
    (pretty_loc p)
| EmptyInput ->
  String ((Ascii (true, false, false, true, false, false, true, false)),
    (String ((Ascii (false, true, true, true, false, true, true, false)),
    (String ((Ascii (false, false, false, false, true, true, true, false)),
    (String ((Ascii (true, false, true, false, true, true, true, false)),
    (String ((Ascii (false, false, true, false, true, true, true, false)),
    (String ((Ascii (false, false, false, false, false, true, false, false)),
    (String ((Ascii (true, false, false, true, false, true, true, false)),
    (String ((Ascii (true, true, false, false, true, true, true, false)),
    (String ((Ascii (false, false, false, false, false, true, false, false)),
    (String ((Ascii (true, false, true, false, false, true, true, false)),
    (String ((Ascii (true, false, true, true, false, true, true, false)),
    (String ((Ascii (false, false, false, false, true, true, true, false)),
    (String ((Ascii (false, false, true, false, true, true, true, false)),
    (String ((Ascii (true, false, false, true, true, true, true, false)),
    EmptyString)))))))))))))))))))))))))))
| InvalidChar (c, p) ->
  append (String ((Ascii (true, false, false, true, false, false, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, true, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, true, false, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, false, true, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), EmptyString))))))))))))))))))))))))))))))))))))
    (append (escape_string (String (c, EmptyString)))
      (append (String ((Ascii (false, false, false, false, false, true,
        false, false)), (String ((Ascii (true, false, false, false, false,
        true, true, false)), (String ((Ascii (false, false, true, false,
        true, true, true, false)), (String ((Ascii (false, false, false,
        false, false, true, false, false)), (String ((Ascii (false, false,
        true, true, false, true, true, false)), (String ((Ascii (true, true,
        true, true, false, true, true, false)), (String ((Ascii (true, true,
        false, false, false, true, true, false)), (String ((Ascii (true,
        false, false, false, false, true, true, false)), (String ((Ascii
        (false, false, true, false, true, true, true, false)), (String
        ((Ascii (true, false, false, true, false, true, true, false)),
        (String ((Ascii (true, true, true, true, false, true, true, false)),
        (String ((Ascii (false, true, true, true, false, true, true, false)),
        (String ((Ascii (false, false, false, false, false, true, false,
        false)), EmptyString)))))))))))))))))))))))))) (pretty_loc p)))
| InvalidStringChar (c, p) ->
  append (String ((Ascii (true, false, false, true, false, false, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (false, true, true, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, true, false, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, false, true, false, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, false, false, true, true,
    false)), (String ((Ascii (true, true, false, false, false, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, false, true, false, false, true, true,
    false)), (String ((Ascii (true, false, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)), (String ((Ascii (true, true, false, false, true, true, true,
    false)), (String ((Ascii (false, false, true, false, true, true, true,
    false)), (String ((Ascii (false, true, false, false, true, true, true,
    false)), (String ((Ascii (true, false, false, true, false, true, true,
    false)), (String ((Ascii (false, true, true, true, false, true, true,
    false)), (String ((Ascii (true, true, true, false, false, true, true,
    false)), (String ((Ascii (false, false, false, false, false, true, false,
    false)),
    EmptyString))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
    (append (escape_string (String (c, EmptyString)))
      (append (String ((Ascii (false, false, false, false, false, true,
        false, false)), (String ((Ascii (true, false, false, false, false,
        true, true, false)), (String ((Ascii (false, false, true, false,
        true, true, true, false)), (String ((Ascii (false, false, false,
        false, false, true, false, false)), (String ((Ascii (false, false,
        true, true, false, true, true, false)), (String ((Ascii (true, true,
        true, true, false, true, true, false)), (String ((Ascii (true, true,
        false, false, false, true, true, false)), (String ((Ascii (true,
        false, false, false, false, true, true, false)), (String ((Ascii
        (false, false, true, false, true, true, true, false)), (String
        ((Ascii (true, false, false, true, false, true, true, false)),
        (String ((Ascii (true, true, true, true, false, true, true, false)),
        (String ((Ascii (false, true, true, true, false, true, true, false)),
        (String ((Ascii (false, false, false, false, false, true, false,
        false)), EmptyString)))))))))))))))))))))))))) (pretty_loc p)))

(** val is_atom_char : ascii -> bool **)

let is_atom_char c =
  if is_alphanum c
  then true
  else string_elem c (String ((Ascii (true, true, true, false, false, true,
         false, false)), (String ((Ascii (true, false, true, true, true,
         true, false, false)), (String ((Ascii (true, false, true, true,
         false, true, false, false)), (String ((Ascii (true, true, false,
         true, false, true, false, false)), (String ((Ascii (false, true,
         false, true, false, true, false, false)), (String ((Ascii (true,
         true, true, true, false, true, false, false)), (String ((Ascii
         (false, true, false, true, true, true, false, false)), (String
         ((Ascii (true, false, false, false, false, true, false, false)),
         (String ((Ascii (true, true, true, true, true, true, false, false)),
         (String ((Ascii (false, false, false, false, false, false, true,
         false)), (String ((Ascii (true, true, false, false, false, true,
         false, false)), (String ((Ascii (false, false, true, false, false,
         true, false, false)), (String ((Ascii (true, false, true, false,
         false, true, false, false)), (String ((Ascii (false, true, true,
         true, true, false, true, false)), (String ((Ascii (false, true,
         true, false, false, true, false, false)), (String ((Ascii (true,
         true, true, true, true, false, true, false)), (String ((Ascii
         (false, false, true, true, true, true, false, false)), (String
         ((Ascii (false, true, true, true, true, true, false, false)),
         (String ((Ascii (false, true, true, true, false, true, false,
         false)), (String ((Ascii (false, false, true, true, false, true,
         false, false)), (String ((Ascii (false, false, true, true, true,
         true, true, false)), (String ((Ascii (false, true, true, true, true,
         true, true, false)),
         EmptyString))))))))))))))))))))))))))))))))))))))))))))
